### ISSUE TITLE
Add inline example of JSON DSG in chapter 5.10

### ISSUE THREAD

**Issue by ritikarawlani** [IHE/ITI.DSGj#19]
Add example of a JSON DSG in chapter 5.10

**Comment by ritikarawlani** [comment]
I've started building an example here. https://docs.google.com/document/d/1wdaqdn5-98A4uB6fQ0aqVQCopppw1nkpHFTVjiw583o/edit#heading=h.wf8w10btda7f 

@litlfred  @JohnMoehrke

**Comment by JohnMoehrke** [comment]
glad to see. Would also be good to have some files checked in to the github repo that we can say are binary signature files. possibly with metadata and such.
