### ISSUE TITLE
Alignment with ISO 17090-4 and Points for Discussion Comment submitted by: IHE-Japan

### ISSUE THREAD

**Issue by findex-miyakawa** [IHE/ITI.DSGj#21]
To ensure consistency and alignment with the ongoing revision of ISO 17090-4, it is recommended to foster discussion and exchange opinions among stakeholders on the following points:

**Specific examples for discussion:**

* **Rationale for limiting Detached mode to ObjectIdByURI format:**
What is the reasoning behind supporting only the ObjectIdByURI format for Detached signatures?
* **Justification for restricting to SHA256:**
What are the grounds for limiting the hash algorithm to SHA256?
* **Clarification on Payload handling in Detached mode:**
The document proposes removing the Payload from the JWS JSON object in Detached mode. Should a zero-byte stream be set instead of removing it entirely?
* **Inclusion of JAdES-B-LTA in Long-Term Signature support:**
Is there a specific reason for excluding JAdES-B-LTA from the scope of Long-Term Signature support?

**Comment by findex-miyakawa** [comment]
Regarding payload processing in detached mode, there appears to be a discrepancy between the handling described in RFC 7515 and that in ETSI's JAdES. Furthermore, we need to ensure consistency with other standards in other areas as well. Since JAdES is also discussed in ISO 17090-4, I would like the relevant parties to exchange opinions and coordinate on these matters.

**Comment by JohnMoehrke** [comment]
@findex-miyakawa We appreciate the observation. Given that we don't have ready access to ISO 17090-4, can you provide guidance on how we can resolve this?

**Comment by findex-miyakawa** [comment]
Dear @JohnMoehrke
IHE holds liaison membership with ISO/TC 215. Could you please request the information through the appropriate liaison representatives?

**Comment by JohnMoehrke** [comment]
I will try that approach, but this has not worked the past few times we have tried. This barrier to accessibility to ISO specifications has prevented us from referencing and thus aligning within the committee. We have had to rely on our membership that do have access to give us actionable recommendations to achieve alignment. Even when we have access, I find that members providing recommended changes is still the best approach. Please provide your recommendation on how we can resolve this.

**Comment by JohnMoehrke** [comment]
IHE has tried to leverage our liaison position with ISO, but ISO is not willing to provide IHE will a copy for our development efforts.

We had not previously included ISO 17090 references. Alignment is not a requirement of our use-cases.

Without the ability to align, and no need to show alignment; I think that we have only the possibility but to reject this request.

**Comment by findex-miyakawa** [comment]
dear @JohnMoehrke 
I understand that Mr. Nusbaum from IHE contacted us last week and he got a draft of the CD version. 
Please obtain the materials through him.

**Comment by JohnMoehrke** [comment]
@findex-miyakawa 
I should have provided the update. yes, we have the CD version.

However, i would still very much appreciate a recommended change proposed from your perspective as one who already understands the 17090 and has identified a problem. The proposed solution by you would be greatly appreciated.

**Comment by JohnMoehrke** [comment]
@findex-miyakawa you can see the proposed resolution in the Pull-Request, do you agree that this resolves your concern?

**Comment by ritikarawlani** [comment]
@findex-miyakawa  RFC7515 says the following for detached " One way to do this is to create a JWS
   in the normal fashion using a representation of the content as the
   payload but then delete the payload representation from the JWS and
   send this modified object to the recipient rather than the JWS."

While ETSI Jades says the following for ObjectIdbyURIHash " When using this mechanism, the JWS Payload shall contribute as an empty stream to the computation of the JWS
Signature Value. "

The IHE-DSG is going with ObjectIdbyURIHash and the proposed PR adds a note to address that
