### ISSUE TITLE
Table 37.1-1: DSG Profile - Actors and Content Modules

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/ITI.DSGj#22]
### Section Number

Table 37.1-1: DSG Profile - Actors and Content Modules

### What is wrong

With the edits done the table is explictly saying thet both content modules are Optional, but they are not.
A content module is required if a specific option is supported.

### Describe the solution you'd like

Add a not below the table that explains how the content modules are related to options

### Priority

{"Medium"=>"Significant issue or clarification. Requires discussion, but should not lead to long debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by JohnMoehrke** [comment]
change sentence
> To claim support with this profile, an actor shall support all required content modules (labeled "R") and may support optional content modules (labeled "O").

to 
> The Content Model implemented will be indicated by the Options declared for the Actor. See section 37.2.
