### ISSUE TITLE
add serialization note for documents in Volume 1, and refer to PCC1

### ISSUE THREAD

**Issue by ritikarawlani** [IHE/ITI.DSGj#5]

**Comment by ritikarawlani** [comment]
Converted comment on merged PR to issue, to keep track.

**Comment by JohnMoehrke** [comment]
reading, I find quite a few things that are poorly defined for enveloping and submissionSet.  Given that these happened after I wrote DSG, I guess this means I was not watching close enough. For detached signature, it is clear that however the signed document is serialized into the Document Sharing binary form, the binary is what the signature hash is calculated across.

**Comment by JohnMoehrke** [comment]
With submissionSet, the document handling is same, but we never say how to hash the submissionSet. We agree this is an XML-Signature problem. I will add this to the readme parking lot

**Comment by JohnMoehrke** [comment]
> With submissionSet, the document handling is same, but we never say how to hash the submissionSet. We agree this is an XML-Signature problem. I will add this to the readme parking lot

This is not a problem as there is no hash calculated across the SubmissionSet. The only thing unique about a submissionSet signature vs otherwise detached signature is that there is an additional entry in the manifest with the SubmissionSet.uniqueId and a zero hash to indicate it is not signed.

**Comment by JohnMoehrke** [comment]
I am unclear on why we are setting b64 to true, thus requiring the content be base64url encoded before being hashed.

**Comment by JohnMoehrke** [comment]
@ritikarawlani is there somewhere in the json signature where a canonicalization specification can be placed?

**Comment by ritikarawlani** [comment]
> @ritikarawlani is there somewhere in the json signature where a canonicalization specification can be placed?

@JohnMoehrke  it can go under 5.10.2 in one of the bullet points. If we're only talking about the payload here then inside 5.10.2.3
